name: siaga_ntb
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.5 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get_cli: ^0.2.30
  google_fonts: ^4.0.4
  google_nav_bar: ^5.0.6
  get: 4.6.5
  flutter: 
    sdk: flutter
  loading_animation_widget: ^1.2.0+4
  camera: ^0.10.5+2
  path_provider: ^2.0.15
  path: ^1.8.2
  webview_flutter: ^4.2.2
  url_launcher: ^6.1.11

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
#   fonts:
#     - family: poppins
#       fonts:
#         - asset: assets/fonts/Poppins-Light.ttf
      
#         - asset: assets/fonts/Poppins-Reguler.ttf
#         - asset: assets/fonts/Poppins-Medium.ttf
#         - asset: assets/fonts/Poppins-SemiBold.ttf
#         - asset: assets/fonts/Poppins-Bold.ttf
  assets: 
    - assets/awan3.png
    - assets/
    - assets/awan4.png
    - assets/bgsplash.png
    - assets/icons/call.png
    - assets/icons/peta.png
    - assets/icons/warning.png
    - assets/icons/gallery.png
    - assets/icons/weather.png
    - assets/icons/info.png
    - assets/icons_2/info2.png
    - assets/icons/call2.png
    - assets/icons_2/call.png
    - assets/icons_2/
    - assets/icons_3/
    - assets/pictures/
    - assets/pict/
  uses-material-design: true

